# core/research_memory.py
#
# Step 13 of the staged self-learning plan.
#
# WHAT THIS DOES: turns resolved hypotheses (SUPPORTED / DISPROVEN, from
# core/hypothesis_engine.py, Step 12) into two durable, git-tracked
# markdown files:
#   - research_memory/lessons.md          -- one entry per resolved
#                                             hypothesis, human- and
#                                             AI-readable, never overwritten
#                                             wholesale (append-only per
#                                             lesson, existing lessons kept
#                                             verbatim on every regenerate).
#   - research_memory/recommendations.md  -- current OPEN/TESTING
#                                             hypotheses, ranked, fully
#                                             regenerated each call (it's a
#                                             snapshot of "what to look at
#                                             next", not a history).
#
# EXPLICITLY NOT INCLUDED, ON PURPOSE -- same philosophy as the rest of
# this layer:
#   - No invented lessons. Every lesson here traces back to a real
#     hypotheses row with real supporting/contradicting experiment counts
#     from core.candidate_gate_results (via Step 9's backtest gate). If a
#     hypothesis has no evidence, it doesn't get a lesson -- it shows up in
#     recommendations.md instead, as something still to test.
#   - No autonomous decisions. This module only reads research_archive.db
#     (pattern_flags / hypotheses / candidate_gate_results) and
#     configs/strategy_registry.json, and writes markdown files. It never
#     touches trade_log.db, risk_manager.py, candidate_config.json, or any
#     strategy file.
#   - update_lessons() is idempotent per hypothesis: a hypothesis already
#     recorded (hypotheses.recorded_in_lessons = 1, set by
#     hypothesis_engine.mark_recorded_in_lessons) is never re-appended, even
#     if its status later changes again (e.g. re-opened via a fresh flag) --
#     that would show up as a *new* hypothesis_id from raise_from_flags,
#     which is deliberately never reused for a resolved one.

import logging
from datetime import datetime
from pathlib import Path

from core import hypothesis_engine

logger = logging.getLogger(__name__)

RESEARCH_MEMORY_DIR = Path(__file__).parent.parent / "research_memory"
LESSONS_PATH = RESEARCH_MEMORY_DIR / "lessons.md"
RECOMMENDATIONS_PATH = RESEARCH_MEMORY_DIR / "recommendations.md"

LESSONS_HEADER = (
    "# Strategy Research Lessons\n\n"
    "Auto-generated by core/research_memory.py from resolved hypotheses in "
    "research_archive.db. Each lesson below is appended once, when its "
    "source hypothesis first resolves to SUPPORTED or DISPROVEN -- never "
    "edited or removed afterward by this script. Safe to hand-edit; manual "
    "edits are preserved (this script only appends new lessons, it never "
    "rewrites the file from scratch).\n\n"
    "---\n"
)


def _ensure_dir() -> None:
    RESEARCH_MEMORY_DIR.mkdir(exist_ok=True)


def _read_existing_lessons() -> str:
    if LESSONS_PATH.exists():
        return LESSONS_PATH.read_text()
    return LESSONS_HEADER


def _lesson_block(h: dict, lesson_number: int) -> str:
    n_sup = len(h["supporting_experiments"])
    n_con = len(h["contradicting_experiments"])
    total = n_sup + n_con
    status_label = "Validated" if h["status"] == "SUPPORTED" else "Disproven"

    lines = [
        "",
        f"## LESSON-{lesson_number:03d}",
        "",
        "Observation:",
        h["statement"],
        "",
        "Evidence:",
        f"{total} experiment(s) ({n_sup} supporting, {n_con} contradicting), "
        f"originally raised from {h['source_dimension_type']}="
        f"{h['source_dimension_value']}.",
        "",
        "Confidence:",
        h["confidence"],
        "",
        "Status:",
        status_label,
        "",
        f"(hypothesis_id: {h['hypothesis_id']}, resolved: {h['updated_at']})",
        "",
        "---",
    ]
    return "\n".join(lines)


def update_lessons(db_path: Path = hypothesis_engine.DB_PATH) -> list:
    """
    Appends a lesson block for every SUPPORTED/DISPROVEN hypothesis that
    hasn't been recorded yet. Returns the list of newly-recorded hypothesis
    dicts. Safe to call every session -- does nothing if there's nothing
    new to record.
    """
    _ensure_dir()
    resolved = []
    for status in ("SUPPORTED", "DISPROVEN"):
        resolved.extend(hypothesis_engine.list_hypotheses(status=status, db_path=db_path))

    to_record = [h for h in resolved if not h["recorded_in_lessons"]]
    if not to_record:
        logger.info("[research_memory] No new resolved hypotheses to record")
        return []

    # Oldest first, so LESSON-NNN numbering reads chronologically.
    to_record.sort(key=lambda h: h["updated_at"])

    existing_text = _read_existing_lessons()
    existing_count = existing_text.count("## LESSON-")

    blocks = []
    for i, h in enumerate(to_record, start=existing_count + 1):
        blocks.append(_lesson_block(h, i))

    with open(LESSONS_PATH, "w") as f:
        f.write(existing_text.rstrip("\n") + "\n" + "\n".join(blocks) + "\n")

    for h in to_record:
        hypothesis_engine.mark_recorded_in_lessons(h["hypothesis_id"], db_path=db_path)

    logger.info(f"[research_memory] Recorded {len(to_record)} new lesson(s)")
    return to_record


def _priority_rank(h: dict) -> tuple:
    """Higher-evidence, higher-confidence OPEN/TESTING hypotheses sort first."""
    conf_rank = {"HIGH": 0, "MEDIUM": 1, "LOW": 2}.get(h["confidence"], 3)
    total_evidence = len(h["supporting_experiments"]) + len(h["contradicting_experiments"])
    return (conf_rank, -total_evidence)


def _recommendation_block(h: dict, priority: int) -> str:
    n_sup = len(h["supporting_experiments"])
    n_con = len(h["contradicting_experiments"])
    lines = [
        f"## Priority {priority}",
        "",
        "Test:",
        h["statement"],
        "",
        "Reason:",
        h["reason"],
    ]
    if n_sup or n_con:
        lines += ["", "Evidence so far:", f"{n_sup} supporting, {n_con} contradicting experiment(s)."]
    if h.get("linked_candidate_id"):
        lines += ["", f"Linked candidate: {h['linked_candidate_id']}"]
    lines += ["", "Required:", h.get("next_test") or "See hypothesis_engine for next step.", "", "---"]
    return "\n".join(lines)


def update_recommendations(db_path: Path = hypothesis_engine.DB_PATH) -> int:
    """
    Fully regenerates recommendations.md from current OPEN/TESTING
    hypotheses, ranked by confidence then evidence volume. This file is a
    snapshot, not a history -- unlike lessons.md it's safe to overwrite
    wholesale each call.
    """
    _ensure_dir()
    live = (hypothesis_engine.list_hypotheses(status="OPEN", db_path=db_path) +
            hypothesis_engine.list_hypotheses(status="TESTING", db_path=db_path))
    live.sort(key=_priority_rank)

    lines = [
        "# Next Research Recommendations",
        "",
        f"Auto-generated by core/research_memory.py at {datetime.now().isoformat()}. "
        "Fully regenerated each run -- reflects current OPEN/TESTING hypotheses only. "
        "See lessons.md for resolved (SUPPORTED/DISPROVEN) findings.",
        "",
        "---",
    ]
    if not live:
        lines += ["", "No open hypotheses right now. Run `python3 -m core.hypothesis_engine raise` "
                       "after a pattern_detection pass to generate some.", ""]
    else:
        for i, h in enumerate(live, start=1):
            lines.append("")
            lines.append(_recommendation_block(h, i))

    with open(RECOMMENDATIONS_PATH, "w") as f:
        f.write("\n".join(lines) + "\n")

    logger.info(f"[research_memory] recommendations.md regenerated ({len(live)} open hypotheses)")
    return len(live)


def read_memory_summary(db_path: Path = hypothesis_engine.DB_PATH) -> dict:
    """
    What the AI/research workflow should retrieve and consider BEFORE
    creating, modifying, or proposing a strategy change. Returns a dict,
    not markdown -- callers (e.g. run_research_session.py) format it
    however's appropriate for the context.
    """
    _ensure_dir()
    lessons_text = LESSONS_PATH.read_text() if LESSONS_PATH.exists() else ""
    recommendations_text = RECOMMENDATIONS_PATH.read_text() if RECOMMENDATIONS_PATH.exists() else ""

    survivors = hypothesis_engine.list_hypotheses(status="SUPPORTED", db_path=db_path)
    failures = hypothesis_engine.list_hypotheses(status="DISPROVEN", db_path=db_path)
    open_hyps = (hypothesis_engine.list_hypotheses(status="OPEN", db_path=db_path) +
                 hypothesis_engine.list_hypotheses(status="TESTING", db_path=db_path))

    return {
        "lessons_md": lessons_text,
        "recommendations_md": recommendations_text,
        "recent_survivors": survivors[:10],
        "recent_failures": failures[:10],
        "open_hypotheses": open_hyps,
    }


def format_memory_considered(summary: dict) -> str:
    """
    Formats read_memory_summary()'s output into a block a research agent
    can state explicitly before acting -- lessons considered, failures
    avoided, survivors considered, hypothesis being tested, and why.
    """
    lines = ["Lessons considered:"]
    lines.append(f"  {len(summary['recent_survivors']) + len(summary['recent_failures'])} "
                 f"resolved lesson(s) in lessons.md.")

    lines.append("")
    lines.append("Previous failures avoided:")
    if summary["recent_failures"]:
        for h in summary["recent_failures"][:5]:
            lines.append(f"  - {h['statement']}")
    else:
        lines.append("  (none recorded yet)")

    lines.append("")
    lines.append("Previous survivors considered:")
    if summary["recent_survivors"]:
        for h in summary["recent_survivors"][:5]:
            lines.append(f"  - {h['statement']}")
    else:
        lines.append("  (none recorded yet)")

    lines.append("")
    lines.append("Hypothesis being tested:")
    if summary["open_hypotheses"]:
        top = summary["open_hypotheses"][0]
        lines.append(f"  [{top['hypothesis_id']}] {top['statement']}")
    else:
        lines.append("  (no open hypothesis -- nothing currently under test)")

    lines.append("")
    lines.append("Reason for this experiment:")
    if summary["open_hypotheses"]:
        lines.append(f"  {summary['open_hypotheses'][0]['reason']}")
    else:
        lines.append("  n/a")

    return "\n".join(lines)


if __name__ == "__main__":
    import sys
    logging.basicConfig(level=logging.INFO)

    if len(sys.argv) < 2 or sys.argv[1] not in ("update", "show"):
        print("Usage: python3 -m core.research_memory update")
        print("       python3 -m core.research_memory show")
        sys.exit(1)

    if sys.argv[1] == "update":
        new_lessons = update_lessons()
        n_reco = update_recommendations()
        print(f"Recorded {len(new_lessons)} new lesson(s). "
              f"recommendations.md now has {n_reco} open hypothesis/hypotheses.")
    elif sys.argv[1] == "show":
        print(format_memory_considered(read_memory_summary()))
